### ISSUE TITLE
Restore-AzVmSnapshot -VmName not found

### ISSUE THREAD

**Issue by NachoHawk** [adbertram/AzureVmSnapshots#3]
When trying to restore snapshot getting error  "The Resource 'Microsoft.Compute/virtualMachines/Win' under resource group 'xxxxxx' was not found." 
 Get-AzVM shows that the resource is there 

CloseError: (:) [Get-AzVM], ### ### ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureVMCommand  

![2019-11-04 17_59_22-pwsh (Admin)](https://user-images.githubusercontent.com/29218701/68168961-2d000580-ff30-11e9-9860-813441a3e8ac.png)

![2019-11-04 17_57_33-pwsh (Admin)](https://user-images.githubusercontent.com/29218701/68169016-4ef98800-ff30-11e9-805e-64e4e7d66bb3.png)

![2019-11-04 18_01_45-Window](https://user-images.githubusercontent.com/29218701/68169021-51f47880-ff30-11e9-8557-671ee7cfa8d1.png)

**Comment by adbertram** [comment]
I just pushed a fix that should resolve this. Let me know how you fare now.

**Comment by ajunlee** [comment]
https://github.com/adbertram/AzureVmSnapshots/blob/e78b38f0a9945d07d50b5fcb65dea119b944368e/Public/Restore-AzVmSnapshot.ps1#L35

It didn't fix this issue and the restore function is broken by it.
The root cause of this issue is the "-" is contained in the vm name, so, split the snapshot name by "-", will split the vm name too.
This fix is trying to split by "AzVmSnapshot-", and it will get the vmname with timestamp. so the vm not found issue is still existing.

According to the naming rule of snapshot, suggest to change following line
`$vmName = ($Snapshot.Name -split 'AzVmSnapshot-')[1]`
to 
`$vmName = $Snapshot.Name.substring("AzVmSnapshot-".length, $Snapshot.Name.LastIndexOf('-') - "AzVmSnapshot-".length)`

**Comment by adbertram** [comment]
@ajunlee Would you mind issuing a PR?
